version: "3.9"
services:
  base:
    image: deepworks/webdna-demo:base
    expose:
      - 80
      - 443
    ports:
    - "80:80"
    - "443:443"
    build:
      context: .
  base-vol:
    extends:
      service: base
    volumes:
      - type: bind
        source: ./public
        target: /var/www/html/public
  # AlmaLinux 8.5 FCGI 8.6.5
  almalinux85-fcgi-865:
    image: deepworks/webdna-demo:almalinux85-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: almalinux/almalinux85.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # AlmaLinux 8.5 FCGI 8.6.4
  almalinux85-fcgi-864:
    image: deepworks/webdna-demo:almalinux85-fcgi-8.6.4
    extends:
      service: almalinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # AlmaLinux 8.5 FCGI 8.6.3
  almalinux85-fcgi-863:
    image: deepworks/webdna-demo:almalinux85-fcgi-8.6.3
    extends:
      service: almalinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # AlmaLinux 8.5 FCGI 8.6.1
  almalinux85-fcgi-861:
    image: deepworks/webdna-demo:almalinux85-fcgi-8.6.1
    extends:
      service: almalinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Alpine 3.12 FCGI 8.6.5
  alpine312-fcgi-865:
    image: deepworks/webdna-demo:alpine312-fcgi-8.6.5
    extends:
      service: base
    volumes:
      - type: bind
        source: ./public
        target: /var/www/localhost/htdocs/public
    build:
      dockerfile: alpine/alpine312.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Alpine-FastCGI-8.6.5"
  # CentOS 7 FCGI 8.6.5
  centos7-fcgi-865:
    image: deepworks/webdna:centos7-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: centos/centos7.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # CentOS 7 FCGI 8.6.4
  centos7-fcgi-864:
    image: deepworks/webdna:centos7-fcgi-8.6.4
    extends:
      service: centos7-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # CentOS 7 FCGI 8.6.3
  centos7-fcgi-863:
    image: deepworks/webdna:centos7-fcgi-8.6.3
    extends:
      service: centos7-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # CentOS 7 FCGI 8.6.1
  centos7-fcgi-861:
    image: deepworks/webdna:centos7-fcgi-8.6.1
    extends:
      service: centos7-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # CentOS 8 FCGI 8.6.5
  centos8-fcgi-865:
    image: deepworks/webdna:centos8-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: centos/centos8.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # CentOS 8 FCGI 8.6.4
  centos8-fcgi-864:
    image: deepworks/webdna:centos8-fcgi-8.6.4
    extends:
      service: centos8-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # CentOS 8 FCGI 8.6.3
  centos8-fcgi-863:
    image: deepworks/webdna:centos8-fcgi-8.6.3
    extends:
      service: centos8-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # CentOS 8 FCGI 8.6.1
  centos8-fcgi-861:
    image: deepworks/webdna:centos8-fcgi-8.6.1
    extends:
      service: centos8-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # RockyLinux 8.5 FCGI 8.6.5
  rockylinux85-fcgi-865:
    image: deepworks/webdna:rockylinux85-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: rockylinux/rockylinux85.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # RockyLinux 8.5 FCGI 8.6.4
  rockylinux85-fcgi-864:
    image: deepworks/webdna:rockylinux85-fcgi-8.6.4
    extends:
      service: rockylinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # RockyLinux 8.5 FCGI 8.6.3
  rockylinux85-fcgi-863:
    image: deepworks/webdna:rockylinux85-fcgi-8.6.3
    extends:
      service: rockylinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # RockyLinux 8.5 FCGI 8.6.1
  rockylinux85-fcgi-861:
    image: deepworks/webdna:rockylinux85-fcgi-8.6.1
    extends:
      service: rockylinux85-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Ubuntu 16.04 FCGI 8.6.5
  ubuntu16-fcgi-865:
    image: deepworks/webdna:ubuntu16-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: ubuntu/ubuntu16.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # Ubuntu 16.04 FCGI 8.6.4
  ubuntu16-fcgi-864:
    image: deepworks/webdna:ubuntu16-fcgi-8.6.4
    extends:
      service: ubuntu16-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # Ubuntu 16.04 FCGI 8.6.3
  ubuntu16-fcgi-863:
    image: deepworks/webdna:ubuntu16-fcgi-8.6.3
    extends:
      service: ubuntu16-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # Ubuntu 16.04 FCGI 8.6.1
  ubuntu16-fcgi-861:
    image: deepworks/webdna:ubuntu16-fcgi-8.6.1
    extends:
      service: ubuntu16-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Ubuntu 18.04 FCGI 8.6.5
  ubuntu18-fcgi-865:
    image: deepworks/webdna:ubuntu18-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: ubuntu/ubuntu18.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # Ubuntu 18.04 FCGI 8.6.4
  ubuntu18-fcgi-864:
    image: deepworks/webdna:ubuntu18-fcgi-8.6.4
    extends:
      service: ubuntu18-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # Ubuntu 18.04 FCGI 8.6.3
  ubuntu18-fcgi-863:
    image: deepworks/webdna:ubuntu18-fcgi-8.6.3
    extends:
      service: ubuntu18-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # Ubuntu 18.04 FCGI 8.6.1
  ubuntu18-fcgi-861:
    image: deepworks/webdna:ubuntu18-fcgi-8.6.1
    extends:
      service: ubuntu18-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Ubuntu 20.04 FCGI 8.6.5
  ubuntu20-fcgi-865:
    image: deepworks/webdna:ubuntu20-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: ubuntu/ubuntu20.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # Ubuntu 20.04 FCGI 8.6.4
  ubuntu20-fcgi-864:
    image: deepworks/webdna:ubuntu20-fcgi-8.6.4
    extends:
      service: ubuntu20-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # Ubuntu 20.04 FCGI 8.6.3
  ubuntu20-fcgi-863:
    image: deepworks/webdna:ubuntu20-fcgi-8.6.3
    extends:
      service: ubuntu20-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # Ubuntu 20.04 FCGI 8.6.1
  ubuntu20-fcgi-861:
    image: deepworks/webdna:ubuntu20-fcgi-8.6.1
    extends:
      service: ubuntu20-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Ubuntu 21.10 FCGI 8.6.5
  ubuntu21-fcgi-865:
    image: deepworks/webdna:ubuntu21-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: ubuntu/ubuntu21.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # Ubuntu 21.10 FCGI 8.6.4
  ubuntu21-fcgi-864:
    image: deepworks/webdna:ubuntu21-fcgi-8.6.4
    extends:
      service: ubuntu21-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # Ubuntu 21.10 FCGI 8.6.3
  ubuntu21-fcgi-863:
    image: deepworks/webdna:ubuntu21-fcgi-8.6.3
    extends:
      service: ubuntu21-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # Ubuntu 21.10 FCGI 8.6.1
  ubuntu21-fcgi-861:
    image: deepworks/webdna:ubuntu21-fcgi-8.6.1
    extends:
      service: ubuntu21-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"
  # Ubuntu 22.04 FCGI 8.6.5
  ubuntu22-fcgi-865:
    image: deepworks/webdna:ubuntu22-fcgi-8.6.5
    extends:
      service: base-vol
    build:
      dockerfile: ubuntu/ubuntu22.Dockerfile
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.5"
  # Ubuntu 22.04 FCGI 8.6.4
  ubuntu22-fcgi-864:
    image: deepworks/webdna:ubuntu22-fcgi-8.6.4
    extends:
      service: ubuntu22-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.4"
  # Ubuntu 22.04 FCGI 8.6.3
  ubuntu22-fcgi-863:
    image: deepworks/webdna:ubuntu22-fcgi-8.6.3
    extends:
      service: ubuntu22-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.3"
  # Ubuntu 22.04 FCGI 8.6.1
  ubuntu22-fcgi-861:
    image: deepworks/webdna:ubuntu22-fcgi-8.6.1
    extends:
      service: ubuntu22-fcgi-865
    build:
      args:
        DNA_EXECUTABLE: "WebDNA-Linux-FastCGI-8.6.1"

