name: Build Docker Image

on:
  push:
    tags:
      - 'centos*-fcgi-*-*'

jobs:
  build_image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checkout utils repo
        uses: actions/checkout@v4
        with:
          repository: deepworks-net/utilities.docker
          path: scripts/utils
        
      - name: Parse tag and set environment
        id: env
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          
          # Get service name by removing the build version (last component)
          SERVICE_NAME=$(echo $TAG | rev | cut -d'-' -f2- | rev)  # centos7-fcgi-865
          
          # Extract other components
          DISTRO_FULL=$(echo $TAG | cut -d'-' -f1)     # centos7
          TYPE=$(echo $TAG | cut -d'-' -f2)            # fcgi
          DNA_VER=$(echo $TAG | cut -d'-' -f3)         # 865
          BUILD_VER=$(echo $TAG | cut -d'-' -f4)       # 1.0.0
          
          ENV_FILE="/${DISTRO_FULL%[0-9]*}/${DISTRO_FULL}.env"
          IMAGE_NAME="deepworks/webdna"
          
          echo "DOCKER_UTILS_ENV=$ENV_FILE" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_VERSION=$TAG" >> $GITHUB_OUTPUT
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_OUTPUT
        
      - name: Build Docker image
        run: |
          chmod +x scripts/build.sh
          scripts/build.sh -c -i ${{ steps.env.outputs.IMAGE_NAME }} -v ${{ steps.env.outputs.IMAGE_VERSION }} -s ${{ steps.env.outputs.SERVICE_NAME }} -t
        env:
          DOCKER_UTILS_ENV: ${{ steps.env.outputs.DOCKER_UTILS_ENV }}