name: Build Docker Image
on:
    push:
      tags:
        - 'webdna:*'
jobs:
  build_image:
        runs-on: ubuntu-latest
        
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
                
          - name: Extract tag info
            id: tag
            run: |
                TAG=${GITHUB_REF#refs/tags/}
                echo "FULL_TAG=$TAG" >> $GITHUB_OUTPUT
                
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
                
          - name: Build Docker image
            uses: docker/build-push-action@v5
            with:
                context: .
                push: false
                load: true
                tags: ${{ steps.tag.outputs.FULL_TAG }}
                cache-from: type=gha
                cache-to: type=gha,mode=max

          - name: Test image
            run: |
                docker image ls
                # Add any additional test commands here
